---
title: "BA Assignement 1"
output: html_document
---

Loading the data
```{r}
stock_data <- read.csv("https://raw.githubusercontent.com/jcbonilla/BusinessAnalytics/master/BAData/Stock%20prices%20HMK1.csv",header=TRUE,stringsAsFactors=FALSE)
```

Exploring the data
```{r}
names(stock_data)
dim(stock_data) #returns dimesnions
class(stock_data)
summary(stock_data)
```
1. Average Price of each company’s share for the given year.
```{r}
average_price_AMZN <- mean(stock_data$AMZN)
average_price_AMZN
average_price_KMX <- mean(stock_data$KMX)
average_price_KMX
average_price_GOOG <- mean(stock_data$GOOG)
average_price_GOOG
average_price_GE <- mean(stock_data$GE)
average_price_GE
```

2. Data Types of all variables in dataset
```{r}
typeof(stock_data)
typeof(stock_data$Date)
typeof(stock_data$AMZN)
typeof(stock_data$KMX)
typeof(stock_data$GOOG)
typeof(stock_data$GE)

```
3. Returns for each company on daily basis
```{r}
daily_returns <- cbind(stock_data[-1,1],apply(stock_data[,-1],2,function(x) diff(x)/head(x,-1)))
daily_returns
# cbind function combines two dataframes, apply function can pass any function to avoid loops and diff function calculates the differences between all consecutive values of a vector, head function - first N rows 

# to calculate stock returns((inital stock price - ending stock price)/ ending stock price)
# quantmod library is used to manipulate stock data in R 

```
4. Cumulative returns for each company’s share for the given year
```{r}
#cumulative returns are total price chnage in stock over aperiod of time 
year_return <- head(stock_data[,2:5],1)/tail(stock_data[,2:5],1)-1
year_return

```
5. Top 5 top returns for the given year
```{r}
apply(daily_returns[,2:5], 2, function(x) rev(sort(as.numeric(x)))[1:5])

```
6. Top 5 worst returns for the given year
```{r}
apply(daily_returns[,2:5], 2, function(x) (sort(as.numeric(x)))[1:5])

```

7. Visulaizing the stock returns for 1 year
```{r}
plot(daily_returns[237:1,2], xaxt= "n", xlab = "date", ylab="daily returns of AMZN", type = 
       "l")
plot(daily_returns[237:1,3], xaxt= "n", xlab = "date", ylab="daily returns of KMX", type = 
       "l")
plot(daily_returns[237:1,4], xaxt= "n", xlab = "date", ylab="daily returns of GOOG", type = 
       "l")
plot(daily_returns[237:1,5], xaxt= "n", xlab = "date", ylab="daily returns of GE", type = 
       "l")


```